server:
  port: 8300

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      #valueEncoder: java
      valueDecoder: java #kryo #

      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 
      port: 6379

#      host: r-uf6ab6446315d8c4.redis.rds.aliyuncs.com #192.168.40.215 #      47.101.132.45

#      password: LwiVq77lKjMW
      #password: yinghuo


spring:
  redis:
    host:
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 30
        max-active: 10
        max-wait: 10000
    database: 7

